# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'less_complex.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 607)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.user_interaction_part = QtWidgets.QWidget(self.splitter)
        self.user_interaction_part.setObjectName("user_interaction_part")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.user_interaction_part)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.central_alf_atom_widget = QtWidgets.QWidget(self.user_interaction_part)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_alf_atom_widget.sizePolicy().hasHeightForWidth())
        self.central_alf_atom_widget.setSizePolicy(sizePolicy)
        self.central_alf_atom_widget.setObjectName("central_alf_atom_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.central_alf_atom_widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.atom_names_combo = QtWidgets.QComboBox(self.central_alf_atom_widget)
        self.atom_names_combo.setObjectName("atom_names_combo")
        self.gridLayout_3.addWidget(self.atom_names_combo, 0, 1, 1, 1)
        self.central_alf_atom_label = QtWidgets.QLabel(self.central_alf_atom_widget)
        self.central_alf_atom_label.setObjectName("central_alf_atom_label")
        self.gridLayout_3.addWidget(self.central_alf_atom_label, 0, 0, 1, 1)
        self.reduce_plotted_points_label = QtWidgets.QLabel(self.central_alf_atom_widget)
        self.reduce_plotted_points_label.setObjectName("reduce_plotted_points_label")
        self.gridLayout_3.addWidget(self.reduce_plotted_points_label, 1, 0, 1, 1)
        self.reduce_points_combo = QtWidgets.QComboBox(self.central_alf_atom_widget)
        self.reduce_points_combo.setObjectName("reduce_points_combo")
        self.gridLayout_3.addWidget(self.reduce_points_combo, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.central_alf_atom_widget)
        self.atoms_to_plot_widget = QtWidgets.QWidget(self.user_interaction_part)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atoms_to_plot_widget.sizePolicy().hasHeightForWidth())
        self.atoms_to_plot_widget.setSizePolicy(sizePolicy)
        self.atoms_to_plot_widget.setObjectName("atoms_to_plot_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.atoms_to_plot_widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.atoms_to_plot_label = QtWidgets.QLabel(self.atoms_to_plot_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atoms_to_plot_label.sizePolicy().hasHeightForWidth())
        self.atoms_to_plot_label.setSizePolicy(sizePolicy)
        self.atoms_to_plot_label.setObjectName("atoms_to_plot_label")
        self.verticalLayout_3.addWidget(self.atoms_to_plot_label)
        self.atoms_to_plot_scroll_area = QtWidgets.QScrollArea(self.atoms_to_plot_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atoms_to_plot_scroll_area.sizePolicy().hasHeightForWidth())
        self.atoms_to_plot_scroll_area.setSizePolicy(sizePolicy)
        self.atoms_to_plot_scroll_area.setWidgetResizable(True)
        self.atoms_to_plot_scroll_area.setObjectName("atoms_to_plot_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 438, 191))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.atoms_to_plot_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.atoms_to_plot_scroll_area)
        self.verticalLayout.addWidget(self.atoms_to_plot_widget)
        self.atom_colors_widget = QtWidgets.QWidget(self.user_interaction_part)
        self.atom_colors_widget.setObjectName("atom_colors_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.atom_colors_widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.atom_colors_label = QtWidgets.QLabel(self.atom_colors_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atom_colors_label.sizePolicy().hasHeightForWidth())
        self.atom_colors_label.setSizePolicy(sizePolicy)
        self.atom_colors_label.setObjectName("atom_colors_label")
        self.verticalLayout_2.addWidget(self.atom_colors_label)
        self.atom_colorscroll_area = QtWidgets.QScrollArea(self.atom_colors_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.atom_colorscroll_area.sizePolicy().hasHeightForWidth())
        self.atom_colorscroll_area.setSizePolicy(sizePolicy)
        self.atom_colorscroll_area.setWidgetResizable(True)
        self.atom_colorscroll_area.setObjectName("atom_colorscroll_area")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 438, 190))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.atom_colorscroll_area.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.atom_colorscroll_area)
        self.verticalLayout.addWidget(self.atom_colors_widget)
        self.pyvista_part = QtWidgets.QWidget(self.splitter)
        self.pyvista_part.setMinimumSize(QtCore.QSize(600, 0))
        self.pyvista_part.setObjectName("pyvista_part")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pyvista_part)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pyvista_frame = QtWidgets.QFrame(self.pyvista_part)
        self.pyvista_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pyvista_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pyvista_frame.setObjectName("pyvista_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pyvista_frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2.addWidget(self.pyvista_frame)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuOpen = QtWidgets.QMenu(self.menuBar)
        self.menuOpen.setObjectName("menuOpen")
        MainWindow.setMenuBar(self.menuBar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuOpen.addAction(self.actionOpen)
        self.menuBar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ALF Visualizer"))
        self.central_alf_atom_label.setText(_translate("MainWindow", "Central Atom"))
        self.reduce_plotted_points_label.setText(_translate("MainWindow", "Reduce plotted points"))
        self.atoms_to_plot_label.setText(_translate("MainWindow", "Which atoms to plot"))
        self.atom_colors_label.setText(_translate("MainWindow", "Atom colors"))
        self.menuOpen.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
